# Generated by Django 5.1.4 on 2025-01-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lesson',
        ),
    ]
